# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField(max_length=11)),
                ('BlackNum', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookCategorytag', models.CharField(max_length=255)),
                ('BookName', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=255)),
                ('Press', models.CharField(max_length=255)),
                ('publicationdate', models.DateTimeField()),
                ('ISBN', models.CharField(max_length=255)),
                ('Edition', models.CharField(max_length=255)),
                ('Price', models.FloatField()),
                ('BookNum', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField(max_length=11)),
                ('BookId', models.IntegerField(max_length=11)),
                ('ReturnTime', models.DateTimeField()),
                ('State', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserNumber', models.CharField(max_length=255)),
                ('PassWord', models.CharField(max_length=255)),
                ('TrueName', models.CharField(max_length=255)),
                ('IsManager', models.IntegerField(max_length=11)),
                ('Professional', models.CharField(max_length=255)),
                ('Grade', models.IntegerField(max_length=11)),
                ('MaxNum', models.IntegerField(max_length=11)),
                ('UserCategory', models.CharField(max_length=255)),
            ],
        ),
    ]
