# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('SubscribeId', models.IntegerField(primary_key=True, serialize=False)),
                ('UserId', models.IntegerField()),
                ('BookId', models.IntegerField()),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('State', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='Price',
            field=models.FloatField(max_length=11),
        ),
    ]
